spring:
  application:
    name: Qualitoolbackend
  datasource:
    url: jdbc:postgresql://localhost:5432/qualitool?useUnicode=true&characterEncoding=utf-8
    username: postgres
    password: postgres
#    data: data.sql
    sql-script-encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        hbm2ddl:
          import_files: data.sql
        connection:
          charSet: UTF-8


server:
  port: 8080
#  port: 8443
#  ssl:
#    enabled: true
#    key-store: keystore.p12
#    key-store-password: w0fx-lhHIvUnMsPZWsKXhrwd
#    key-store-type: PKCS12
#    key-alias: tomcat
